### ISSUE TITLE
bed_size_X and bed_size_Y variables not substituted (Slic3r 1.2.9)

### ISSUE THREAD

**Issue by PxT** [iamnotachoice/Multi-Extrusion-post-processing-scripts-for-Slic3r#4]
The bed_size_X and bed_size_Y variables are not available in Slic3r 1.2.9 and so do not get substituted into the template Start GCODE.  Works fine with Slic3r 1.1.7 so these must have been removed for some reason.

**Comment by flaterichd** [comment]
+1

**Comment by makertum** [comment]
True, thats more a slic3r bug, though, just type them in manually.
